### ISSUE TITLE
wallet operations test page

### ISSUE THREAD

**Issue by elv-todd** [eluv-io/elv-media-wallet#25]
# DApp operations test page

## basic operations

we want to create a test app that shows all the basic wallet functions, for sharing with customers.  functions include:
- create client-side access token 
- wallet signing
- verification of NFT ownership
- generate embed url for playout of gated content (see https://embed.v3.contentfabric.io/) + player

at top of page:
- select "main" or "demo" network with a toggle

once client is logged in:
- add selector for marketplace

as design motivation, see the metamask test-dapp: https://metamask.github.io/test-dapp/

we can start from elv-media-wallet's existing test apps, either
- test/client.js. ✔️ 
- test/login.js

after this, we want to add cross-chain support.

## cross-chain contract verification

use
```
 async CallContractMethod({
  "contractAddress": "...",
  "methodName": "balanceOf"
});
```
and simply check it for `amount > 1` to  return success;
see https://eluv-io.github.io/elv-client-js/module-ElvClient_Contracts.html#.CallContractMethod

**Comment by elv-kevin** [comment]
Use test/client.js, because that doesn't use the frame client.

**Comment by elv-todd** [comment]
I think we also want:
- ability to toggle `main` vs `demo`
  -- set tenant slug
  -- set marketplace slug

**Comment by elv-todd** [comment]
proceeding along the lines of this:
![wallet-op-test](https://user-images.githubusercontent.com/108554594/184790838-4cb69f9c-74e8-4746-bf04-7ac8746f2d4c.png)

**Comment by elv-todd** [comment]
https://github.com/eluv-io/elv-media-wallet/pull/27

**Comment by elv-todd** [comment]
can probably merge what we have, and then use a new PR for cross-chain
